sudo: required
language: node_js
cache:
  yarn: true
notifications:
  email: false
branches:
  only:
    - master
node_js:
  - "8"
services:
  - docker
before_script:
  - make fixture-build
  - make fixture-up
script:
  - make test-coveralls
