sudo: required
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
branches:
  only:
    - master
node_js:
  - "6"
  - "4"
services:
  - docker
install:
  - npm install
before_script:
  - npm prune
  - ./test/fixture/pretest.sh
script:
  - make test-coveralls
