sudo: required
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
branches:
  only:
    - master
node_js:
  - "6"
  - "4"
services:
  - docker
install:
  - npm install
  - npm prune
before_script:
  - make fixture-build
  - make fixture-up
script:
  - make test-coveralls
